# Generated by Django 6.1.1 on 2026-10-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('utor', models.CharField(max_length=100, verbose_name='Autor')),
                ('ano', models.PositiveIntegerField()),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('ategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=100)),
                ('data_retirada', models.DateField(auto_now_add=True, verbose_name='Data de retirada')),
                ('devolvido', models.BooleanField(default=False)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='acervo.livro')),
            ],
        ),
    ]
