# Generated by Django 6.1.1 on 2026-10-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='utor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='ategoria',
            new_name='categoria',
        ),
    ]
